"""
Integration tests: ISA Conformance ↔ FluxVM ↔ Fleet Systems.

Bridges the isa_conformance.py translation layer with flux_vm.py execution,
the natural-language Interpreter, and fleet health-check message handling.

Coverage targets not in test_isa_conformance.py:
  - FluxVM execution correctness (no prior pytest coverage)
  - Assembler → validate → translate → VM execution pipeline
  - Semantic equivalence after v1↔v2 translation
  - Interpreter-generated bytecode conformance against ISA dialects
  - Fleet health-check message format validation
  - Registry fleet_report consistency with actual VM validation
  - Program equivalence across translation round-trips (register-level)
"""

import json
import os
import struct
import sys
import unittest

# Ensure parent directory is on path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from isa_conformance import (
    ISADialect,
    ISATranslator,
    ConformanceVector,
    ISARegistry,
    Op,
    InsnFormat,
    OP_FORMAT,
    TranslationResult,
    TranslationIssue,
    build_translator,
)
from flux_vm import FluxVM, Assembler, Disassembler, Interpreter, Vocabulary


# ─── Helpers ─────────────────────────────────────────────────────────────────

def make_v1_bytecode(*instructions) -> bytes:
    """Build v1 bytecode from (mnemonic, *operands) tuples."""
    v1 = ISADialect.v1()
    buf = bytearray()
    for item in instructions:
        if isinstance(item, (list, tuple)):
            mn = item[0]
            operands = item[1:]
        else:
            mn = item
            operands = []
        op = v1.opcode_for(mn)
        assert op is not None, f"Unknown mnemonic: {mn}"
        buf.append(op)
        if mn == "HALT":
            pass
        elif mn == "DEC":
            buf.append(operands[0])
        elif mn in ("IADD", "IMUL", "IDIV"):
            buf.extend(operands[:3])
        elif mn == "MOVI":
            buf.append(operands[0])
            buf.extend(struct.pack("<h", operands[1]))
        elif mn == "JNZ":
            buf.append(operands[0])
            buf.extend(struct.pack("<h", operands[1]))
    return bytes(buf)


def assemble_and_run(asm_text: str, result_reg: int = 0):
    """Assemble v1 assembly text and run on FluxVM. Returns register value."""
    bc = Assembler().assemble(asm_text)
    vm = FluxVM(bc)
    vm.execute()
    return vm.reg(result_reg)


# ═════════════════════════════════════════════════════════════════════════════
# 1. FluxVM execution tests (never had pytest coverage before)
# ═════════════════════════════════════════════════════════════════════════════

class TestFluxVMExecution(unittest.TestCase):
    """Verify FluxVM execution correctness across all opcodes."""

    def test_halt_empty(self):
        vm = FluxVM(bytes([0x80]))
        vm.execute()
        self.assertTrue(vm.halted)
        self.assertIsNone(vm.error)

    def test_movi(self):
        bc = bytes([0x2B, 0x00, 0x2A, 0x00]) + bytes([0x80])  # MOVI R0,42; HALT
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(0), 42)

    def test_mov(self):
        bc = bytes([0x2B, 0x01, 0x63, 0x00])  # MOVI R1, 99
        bc += bytes([0x2C, 0x00, 0x01])        # MOV R0, R1
        bc += bytes([0x80])                      # HALT
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(0), 99)

    def test_iadd(self):
        # MOVI R0,7; MOVI R1,3; IADD R0,R0,R1; HALT
        bc = bytes([0x2B, 0x00, 0x07, 0x00,
                     0x2B, 0x01, 0x03, 0x00,
                     0x08, 0x00, 0x00, 0x01,
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(0), 10)

    def test_isub(self):
        bc = bytes([0x2B, 0x00, 0x0A, 0x00,  # MOVI R0, 10
                     0x2B, 0x01, 0x03, 0x00,  # MOVI R1, 3
                     0x09, 0x00, 0x00, 0x01,  # ISUB R0,R0,R1
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(0), 7)

    def test_imul(self):
        bc = bytes([0x2B, 0x00, 0x06, 0x00,  # MOVI R0, 6
                     0x2B, 0x01, 0x07, 0x00,  # MOVI R1, 7
                     0x0A, 0x02, 0x00, 0x01,  # IMUL R2,R0,R1
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(2), 42)

    def test_idiv(self):
        bc = bytes([0x2B, 0x00, 0x14, 0x00,  # MOVI R0, 20
                     0x2B, 0x01, 0x04, 0x00,  # MOVI R1, 4
                     0x0B, 0x02, 0x00, 0x01,  # IDIV R2,R0,R1
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(2), 5)

    def test_idiv_by_zero(self):
        bc = bytes([0x2B, 0x00, 0x2A, 0x00,  # MOVI R0, 42
                     0x0B, 0x02, 0x00, 0x01,  # IDIV R2,R0,R1 (R1=0)
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertIsNotNone(vm.error)
        self.assertIn("Division by zero", vm.error)

    def test_inc(self):
        bc = bytes([0x2B, 0x00, 0x05, 0x00,  # MOVI R0, 5
                     0x0E, 0x00,              # INC R0
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(0), 6)

    def test_dec(self):
        bc = bytes([0x2B, 0x00, 0x05, 0x00,  # MOVI R0, 5
                     0x0F, 0x00,              # DEC R0
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(0), 4)

    def test_cmp_less(self):
        bc = bytes([0x2B, 0x00, 0x03, 0x00,  # MOVI R0, 3
                     0x2B, 0x01, 0x05, 0x00,  # MOVI R1, 5
                     0x0D, 0x00, 0x01,        # CMP R0,R1
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(13), -1)

    def test_cmp_equal(self):
        bc = bytes([0x2B, 0x00, 0x07, 0x00,  # MOVI R0, 7
                     0x2B, 0x01, 0x07, 0x00,  # MOVI R1, 7
                     0x0D, 0x00, 0x01,        # CMP R0,R1
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(13), 0)

    def test_cmp_greater(self):
        bc = bytes([0x2B, 0x00, 0x09, 0x00,  # MOVI R0, 9
                     0x2B, 0x01, 0x04, 0x00,  # MOVI R1, 4
                     0x0D, 0x00, 0x01,        # CMP R0,R1
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(13), 1)

    def test_jnz_taken(self):
        """JNZ when register is non-zero should jump (back to a label)."""
        # Use assembler to get correct relative offsets
        bc = Assembler().assemble(
            "MOVI R0, 1\nMOVI R1, 0\nloop: JNZ R0, loop\nMOVI R1, 99\nHALT"
        )
        # JNZ loops back forever → max_cycles should stop it
        vm = FluxVM(bc, max_cycles=100)
        vm.execute()
        self.assertFalse(vm.halted)
        self.assertEqual(vm.cycles, 100)

    def test_jnz_not_taken(self):
        """JNZ when register is zero should NOT jump."""
        bc = bytes([0x2B, 0x00, 0x00, 0x00,  # MOVI R0, 0
                     0x2B, 0x01, 0x01, 0x00,  # MOVI R1, 1
                     0x06, 0x00, 0x01, 0x00,  # JNZ R0, +1 (skip HALT)
                     0x80])                      # HALT
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(1), 1)
        self.assertTrue(vm.halted)

    def test_jz_taken(self):
        """JZ when register is zero should jump."""
        # Use assembler with label for correct offset
        bc = Assembler().assemble(
            "MOVI R0, 0\nMOVI R1, 5\nJZ R0, skip\nMOVI R1, 99\nskip: HALT"
        )
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(1), 5)
        self.assertTrue(vm.halted)

    def test_jmp(self):
        """JMP unconditionally jumps."""
        # Use assembler with label for correct offset
        bc = Assembler().assemble(
            "MOVI R0, 1\nJMP skip\nMOVI R0, 2\nskip: HALT"
        )
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(0), 1)
        self.assertTrue(vm.halted)

    def test_push_pop(self):
        bc = bytes([0x2B, 0x00, 0x2A, 0x00,  # MOVI R0, 42
                     0x01, 0x00,              # PUSH R0
                     0x2B, 0x01, 0x00, 0x00,  # MOVI R1, 0
                     0x02, 0x02,              # POP R2
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(2), 42)

    def test_pop_empty_stack(self):
        bc = bytes([0x02, 0x00, 0x80])  # POP R0; HALT
        vm = FluxVM(bc)
        vm.execute()
        self.assertIsNotNone(vm.error)
        self.assertIn("Stack underflow", vm.error)

    def test_push_pop_lifo(self):
        bc = bytes([0x2B, 0x00, 0x01, 0x00,  # MOVI R0, 1
                     0x2B, 0x01, 0x02, 0x00,  # MOVI R1, 2
                     0x01, 0x00,              # PUSH R0
                     0x01, 0x01,              # PUSH R1
                     0x02, 0x02,              # POP R2
                     0x02, 0x03,              # POP R3
                     0x80])
        vm = FluxVM(bc)
        vm.execute()
        self.assertEqual(vm.reg(2), 2)  # LIFO: last pushed = first popped
        self.assertEqual(vm.reg(3), 1)

    def test_max_cycles_protection(self):
        """VM should stop when PC exceeds bytecode without HALT."""
        # MOVI R0, 1 → single instruction, no HALT
        # VM exits because pc >= len(bc), not because of max_cycles
        bc = bytes([0x2B, 0x00, 0x01, 0x00])
        vm = FluxVM(bc, max_cycles=5)
        vm.execute()
        self.assertFalse(vm.halted)
        self.assertLessEqual(vm.cycles, 5)
        self.assertIsNone(vm.error)

    def test_result_returns_none_on_error(self):
        bc = bytes([0x02, 0x00])  # POP R0 — no stack
        vm = FluxVM(bc)
        vm.execute()
        self.assertIsNone(vm.result(0))

    def test_registers_initialized_zero(self):
        vm = FluxVM(bytes([0x80]))
        vm.execute()
        for i in range(16):
            self.assertEqual(vm.reg(i), 0)


# ═════════════════════════════════════════════════════════════════════════════
# 2. Assembler ↔ ISA conformance validation pipeline
# ═════════════════════════════════════════════════════════════════════════════

class TestAssemblerConformance(unittest.TestCase):
    """Verify that bytecode produced by the Assembler conforms to v1 dialect."""

    def test_simple_program_conforms(self):
        asm = Assembler()
        bc = asm.assemble("MOVI R0, 42\nHALT")
        v1 = ISADialect.v1()
        issues = v1.validate_bytecode(bc)
        self.assertEqual(len(issues), 0)

    def test_complex_program_conforms(self):
        asm_text = (
            "MOVI R0, 10\nMOVI R1, 3\n"
            "IADD R2, R0, R1\n"
            "IMUL R2, R2, R0\n"
            "DEC R2\n"
            "HALT"
        )
        bc = Assembler().assemble(asm_text)
        v1 = ISADialect.v1()
        issues = v1.validate_bytecode(bc)
        self.assertEqual(len(issues), 0)

    def test_loop_program_conforms(self):
        asm_text = (
            "MOVI R0, 5\nMOVI R1, 0\n"
            "loop: IADD R1, R1, R0\n"
            "DEC R0\nJNZ R0, loop\n"
            "HALT"
        )
        bc = Assembler().assemble(asm_text)
        v1 = ISADialect.v1()
        issues = v1.validate_bytecode(bc)
        self.assertEqual(len(issues), 0)

    def test_v1_dialect_opcodes_conform(self):
        """Program using only v1-dialect opcodes should conform to v1."""
        # v1 dialect: MOVI, IADD, IMUL, IDIV, DEC, JNZ, HALT
        asm_text = (
            "MOVI R0, 1\nMOVI R1, 1\n"
            "IADD R0, R0, R1\n"
            "IMUL R2, R0, R1\n"
            "IDIV R3, R0, R1\n"
            "DEC R0\n"
            "JNZ R1, 0\n"
            "HALT"
        )
        bc = Assembler().assemble(asm_text)
        v1 = ISADialect.v1()
        issues = v1.validate_bytecode(bc)
        self.assertEqual(len(issues), 0)

    def test_vm_only_opcodes_not_in_v1_dialect(self):
        """VM-only opcodes (ISUB, INC, MOV, CMP, JZ, JMP, PUSH, POP) \
        are NOT in the v1 ISA dialect."""
        v1 = ISADialect.v1()
        vm_only = ["ISUB", "INC", "MOV", "CMP", "JZ", "JMP", "PUSH", "POP"]
        for mn in vm_only:
            self.assertIsNone(v1.opcode_for(mn),
                f"{mn} should not be in v1 dialect")

    def test_vm_only_opcodes_fail_v1_validation(self):
        """Bytecode with VM-only opcodes should not conform to v1 dialect."""
        asm_text = "MOVI R0, 1\nISUB R0, R0, R1\nHALT"
        bc = Assembler().assemble(asm_text)
        v1 = ISADialect.v1()
        issues = v1.validate_bytecode(bc)
        self.assertGreater(len(issues), 0)

    def test_assembled_bytecode_not_v2_conformant(self):
        """v1 assembler output should NOT fully conform to v2 dialect."""
        bc = Assembler().assemble("MOVI R0, 42\nHALT")
        v2 = ISADialect.v2()
        issues = v2.validate_bytecode(bc)
        self.assertGreater(len(issues), 0)

    def test_assembler_bytecode_size_matches_isa(self):
        """Assembler instruction sizes must match ISA format table."""
        asm_text = "MOVI R0, 1\nIADD R0, R0, R0\nDEC R0\nHALT"
        bc = Assembler().assemble(asm_text)
        # MOVI=4, IADD=4, DEC=2, HALT=1 → 11 bytes
        self.assertEqual(len(bc), 11)


# ═════════════════════════════════════════════════════════════════════════════
# 3. Translation ↔ VM semantic equivalence
# ═════════════════════════════════════════════════════════════════════════════

class TestTranslationSemantics(unittest.TestCase):
    """Verify programs produce equivalent results across translation."""

    def _run_v1(self, asm_text: str, result_reg: int = 0) -> int:
        bc = Assembler().assemble(asm_text)
        vm = FluxVM(bc)
        vm.execute()
        return vm.reg(result_reg)

    def test_translate_v1_to_v2_preserves_operands(self):
        """After v1→v2 translation, MOVI immediate is intact."""
        v1, v2 = ISADialect.v1(), ISADialect.v2()
        t = ISATranslator(v1, v2)
        bc = make_v1_bytecode(("MOVI", 0, 42), ("HALT",))
        result = t.translate(bc)
        out = result.bytecode
        # Operand bytes should be identical: [rd=0x00, i16_lo, i16_hi]
        self.assertEqual(out[1], 0x00)  # R0
        val = struct.unpack("<h", out[2:4])[0]
        self.assertEqual(val, 42)

    def test_translate_preserves_register_operands(self):
        """Register operands survive translation (e.g., IADD R3,R5,R7)."""
        v1, v2 = ISADialect.v1(), ISADialect.v2()
        t = ISATranslator(v1, v2)
        bc = make_v1_bytecode(("IADD", 3, 5, 7), ("HALT",))
        result = t.translate(bc)
        out = result.bytecode
        # Second byte should still be R3=0x03, etc.
        self.assertEqual(out[1], 3)
        self.assertEqual(out[2], 5)
        self.assertEqual(out[3], 7)

    def test_round_trip_byte_identity(self):
        """v1→v2→v1 round-trip must produce identical bytes."""
        v1, v2 = ISADialect.v1(), ISADialect.v2()
        t_fwd = ISATranslator(v1, v2)
        t_back = ISATranslator(v2, v1)
        original = make_v1_bytecode(
            ("MOVI", 0, 10), ("IADD", 0, 0, 0), ("DEC", 0), ("HALT",)
        )
        translated = t_fwd.translate(original).bytecode
        roundtrip = t_back.translate(translated).bytecode
        self.assertEqual(roundtrip, original)

    def test_round_trip_register_semantics(self):
        """After v1→v2→v1 round-trip, VM execution must be identical."""
        v1, v2 = ISADialect.v1(), ISADialect.v2()
        t_fwd = ISATranslator(v1, v2)
        t_back = ISATranslator(v2, v1)

        # Build original v1 bytecode from assembler
        asm_text = "MOVI R0, 10\nMOVI R1, 3\nIADD R0, R0, R1\nHALT"
        original_bc = Assembler().assemble(asm_text)

        # Execute original
        vm1 = FluxVM(original_bc)
        vm1.execute()
        result_before = vm1.reg(0)

        # Round-trip
        translated = t_fwd.translate(original_bc).bytecode
        roundtrip = t_back.translate(translated).bytecode

        # Execute round-tripped
        vm2 = FluxVM(roundtrip)
        vm2.execute()
        result_after = vm2.reg(0)

        self.assertEqual(result_before, result_after)
        self.assertEqual(result_before, 13)

    def test_translation_coverage_matches_registry_score(self):
        """TranslationResult.coverage should align with ConformanceVector score."""
        v1 = ISADialect.v1()
        v2 = ISADialect.v2()
        cv = ConformanceVector(v1, v2)
        report = cv.report()

        # Build a program using all v1 opcodes
        bc = make_v1_bytecode(
            ("MOVI", 0, 1), ("IADD", 0, 0, 1), ("IMUL", 0, 0, 0),
            ("IDIV", 0, 0, 1), ("DEC", 0), ("JNZ", 0, 0), ("HALT",)
        )

        t = ISATranslator(v1, v2)
        result = t.translate(bc)

        # Program with all portable ops should have 100% coverage
        self.assertEqual(result.coverage, 1.0)
        # Score should reflect full portability of v1→v2
        self.assertGreaterEqual(report.score, 0.85)

    def test_unmapped_program_vm_fails(self):
        """A v2-only program (SUB) translated to v1 should leave unmapped 0xFF."""
        v2, v1 = ISADialect.v2(), ISADialect.v1()
        t = ISATranslator(v2, v1, strict=False)
        # SUB R0, R0, R0 (v2 only)
        bc = bytes([0x21, 0x00, 0x00, 0x00, 0x00])  # SUB + HALT
        result = t.translate(bc)
        self.assertEqual(result.unmapped, 1)
        self.assertEqual(result.bytecode[0], 0xFF)  # placeholder


# ═════════════════════════════════════════════════════════════════════════════
# 4. Interpreter ↔ ISA conformance
# ═════════════════════════════════════════════════════════════════════════════

class TestInterpreterConformance(unittest.TestCase):
    """Verify that Interpreter-generated bytecode conforms to v1 ISA."""

    def setUp(self):
        self.interp = Interpreter()
        self.v1 = ISADialect.v1()

    def test_addition_bytecode_conforms(self):
        result, msg = self.interp.run("compute 7 + 5")
        # We need to check the bytecode directly
        vocab = self.interp.vocab
        match = vocab.match("compute 7 + 5")
        self.assertIsNotNone(match)
        asm = match['assembly'].replace('${a}', '7').replace('${b}', '5')
        bc = Assembler().assemble(asm)
        issues = self.v1.validate_bytecode(bc)
        self.assertEqual(len(issues), 0)

    def test_factorial_bytecode_conforms(self):
        vocab = self.interp.vocab
        match = vocab.match("factorial of 5")
        self.assertIsNotNone(match)
        asm = match['assembly'].replace('${n}', '5')
        bc = Assembler().assemble(asm)
        issues = self.v1.validate_bytecode(bc)
        self.assertEqual(len(issues), 0)

    def test_v1_only_vocab_patterns_conform(self):
        """Vocabulary patterns using only v1-dialect opcodes must produce \
        valid v1 bytecode."""
        vocab = Vocabulary().get_builtin()
        v1 = ISADialect.v1()

        # Only patterns that exclusively use v1 opcodes \
        # (MOVI, IADD, IMUL, IDIV, DEC, JNZ, HALT)
        v1_only_patterns = [
            "compute 3 + 4",      # MOVI, IADD
            "compute 6 * 7",      # MOVI, IMUL
            "compute 20 / 4",     # MOVI, IDIV
            "factorial of 5",     # MOVI, IMUL, DEC, JNZ
            "double 21",          # MOVI, IADD
            "square 7",           # MOVI, IMUL
            "power of 2 to 8",    # MOVI, IMUL, DEC, JNZ
            "hello",              # MOVI
        ]

        for text in v1_only_patterns:
            with self.subTest(text=text):
                match = vocab.match(text)
                self.assertIsNotNone(match, f"No vocab match for: {text}")
                # Substitute template variables
                asm = match['assembly']
                for k, v in match['groups'].items():
                    asm = asm.replace('${' + k + '}', str(v))
                bc = Assembler().assemble(asm)
                issues = v1.validate_bytecode(bc)
                self.assertEqual(len(issues), 0,
                    f"Vocab pattern '{text}' produced invalid v1 bytecode")

    def test_extended_vocab_patterns_use_vm_only_opcodes(self):
        """Some vocabulary patterns use opcodes beyond v1 dialect \
        (ISUB, MOV, JZ, CMP, JMP) — expected behavior."""
        vocab = Vocabulary().get_builtin()
        v1 = ISADialect.v1()

        extended_patterns = [
            "compute 10 - 2",     # uses ISUB
            "fibonacci of 7",     # uses MOV
            "sum 1 to 10",        # uses CMP, JZ, JMP, INC
        ]

        for text in extended_patterns:
            with self.subTest(text=text):
                match = vocab.match(text)
                self.assertIsNotNone(match)
                asm = match['assembly']
                for k, v in match['groups'].items():
                    asm = asm.replace('${' + k + '}', str(v))
                bc = Assembler().assemble(asm)
                issues = v1.validate_bytecode(bc)
                # These patterns use VM-only opcodes, so they should NOT \
                # fully conform to v1
                self.assertGreater(len(issues), 0,
                    f"'{text}' should use VM-only opcodes not in v1 dialect")

    def test_interpreter_results_correct(self):
        """Interpreter should produce correct results for all patterns."""
        interp = Interpreter()
        test_cases = [
            ("compute 3 + 4", 7),
            ("compute 10 - 2", 8),
            ("compute 6 * 7", 42),
            ("compute 20 / 4", 5),
            ("factorial of 5", 120),
            ("fibonacci of 7", 13),
            ("double 21", 42),
            ("square 7", 49),
            ("sum 1 to 10", 55),
            ("power of 2 to 8", 256),
            ("hello", 42),
        ]
        for text, expected in test_cases:
            with self.subTest(text=text):
                result, msg = interp.run(text)
                self.assertEqual(result, expected,
                    f"Interpreter returned {result}, expected {expected} for '{text}'")
                self.assertIn("OK", msg)


# ═════════════════════════════════════════════════════════════════════════════
# 5. Fleet health-check message validation
# ═════════════════════════════════════════════════════════════════════════════

class TestFleetHealthMessages(unittest.TestCase):
    """Validate fleet health-check message formats for inter-agent compatibility."""

    HEALTH_CHECK_SCHEMA = {"type", "from", "timestamp", "message", "respond_within"}
    HEALTH_RESPONSE_SCHEMA = {"type", "from", "timestamp", "status",
                               "responding_to", "message", "notes",
                               "session_count", "last_activity"}

    def test_health_check_format(self):
        """Health check messages should have required fields."""
        path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "for-fleet", "health-check-2026-04-12_171927.json"
        )
        if not os.path.exists(path):
            self.skipTest("Health check file not found")
        with open(path) as f:
            data = json.load(f)
        self.assertEqual(data["type"], "HEALTH_CHECK")
        for field in self.HEALTH_CHECK_SCHEMA:
            self.assertIn(field, data, f"Missing field '{field}' in health check")

    def test_health_response_format(self):
        """Health response messages should have required fields."""
        path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "from-fleet", "health-response-2026-04-13.json"
        )
        if not os.path.exists(path):
            self.skipTest("Health response file not found")
        with open(path) as f:
            data = json.load(f)
        self.assertEqual(data["type"], "HEALTH_RESPONSE")
        self.assertEqual(data["status"], "healthy")
        for field in self.HEALTH_RESPONSE_SCHEMA:
            self.assertIn(field, data, f"Missing field '{field}' in health response")

    def test_health_response_references_check(self):
        """Health response should reference the health check it answers."""
        check_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "for-fleet", "health-check-2026-04-12_171927.json"
        )
        resp_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "from-fleet", "health-response-2026-04-13.json"
        )
        if not os.path.exists(check_path) or not os.path.exists(resp_path):
            self.skipTest("Health message files not found")

        with open(resp_path) as f:
            resp = json.load(f)
        # responding_to should contain the check filename
        self.assertIn("health-check", resp["responding_to"])

    def test_health_message_serializable(self):
        """Health messages should be JSON-serializable and deserializable."""
        sample_check = {
            "type": "HEALTH_CHECK",
            "from": "test-agent",
            "timestamp": "2026-04-13T00:00:00Z",
            "message": "Are you ok?",
            "respond_within": 600,
        }
        serialized = json.dumps(sample_check)
        deserialized = json.loads(serialized)
        self.assertEqual(deserialized["type"], "HEALTH_CHECK")

    def test_conformance_report_json_serializable(self):
        """ConformanceReport fields should be JSON-safe."""
        v1, v2 = ISADialect.v1(), ISADialect.v2()
        cv = ConformanceVector(v1, v2)
        report = cv.report()
        # Should not raise
        data = {
            "source": report.source_name,
            "target": report.target_name,
            "score": report.score,
            "portable": report.portable_operations,
            "total": report.total_operations,
            "source_only": report.source_only,
            "target_only": report.target_only,
        }
        serialized = json.dumps(data)
        self.assertIsInstance(serialized, str)


# ═════════════════════════════════════════════════════════════════════════════
# 6. Registry fleet_report ↔ actual VM validation consistency
# ═════════════════════════════════════════════════════════════════════════════

class TestRegistryVMConsistency(unittest.TestCase):
    """Ensure ISARegistry fleet_report scores match real VM validation."""

    def test_v1_program_scores_perfect_v1(self):
        reg = ISARegistry()
        bc = make_v1_bytecode(("MOVI", 0, 1), ("HALT",))
        scores = reg.fleet_report(bc)
        self.assertEqual(scores["v1"], 1.0)

    def test_v1_program_scores_lower_v2(self):
        """v1 bytecode should score lower against v2 (different opcodes)."""
        reg = ISARegistry()
        bc = make_v1_bytecode(("MOVI", 0, 1), ("IADD", 0, 0, 1), ("HALT",))
        scores = reg.fleet_report(bc)
        # v1 opcodes (0x2B, 0x08, 0x80) are not in v2 dialect
        self.assertLess(scores["v2"], 1.0)

    def test_v2_program_scores_perfect_v2(self):
        v2 = ISADialect.v2()
        reg = ISARegistry()
        bc = bytes([0x30, 0x00, 0x01, 0x00, 0x00])  # MOVI R0,1; HALT (v2)
        scores = reg.fleet_report(bc)
        self.assertEqual(scores["v2"], 1.0)

    def test_empty_program_all_perfect(self):
        reg = ISARegistry()
        scores = reg.fleet_report(b"")
        for name, score in scores.items():
            self.assertEqual(score, 1.0, f"Empty program should score 1.0 for {name}")

    def test_custom_dialect_fleet_report(self):
        """Registry with custom dialect should include it in fleet_report."""
        reg = ISARegistry()
        reg.register(ISADialect.custom("esp32", 1, {"HALT": 0xFF, "MOVI": 0xAA}))
        bc = make_v1_bytecode(("HALT",))
        scores = reg.fleet_report(bc)
        self.assertIn("esp32", scores)
        self.assertLess(scores["esp32"], 1.0)  # v1 HALT ≠ esp32 HALT

    def test_compatibility_matrix_symmetry_check(self):
        """Compatibility matrix should be well-formed for all pairs."""
        reg = ISARegistry()
        reg.register(ISADialect.custom("v3", 3, {
            "HALT": 0x00, "ADD": 0x20, "SUB": 0x21,
            "MUL": 0x22, "DIV": 0x23, "MOVI": 0x30,
        }))
        matrix = reg.compatibility_matrix()
        names = reg.dialect_names
        # Self-compatibility must be 1.0
        for name in names:
            self.assertEqual(matrix[name][name], 1.0)
        # All entries should be in [0.0, 1.0]
        for a in names:
            for b in names:
                self.assertGreaterEqual(matrix[a][b], 0.0)
                self.assertLessEqual(matrix[a][b], 1.0)


# ═════════════════════════════════════════════════════════════════════════════
# 7. Disassembler ↔ ISA conformance
# ═════════════════════════════════════════════════════════════════════════════

class TestDisassemblerConformance(unittest.TestCase):
    """Verify disassembler output aligns with ISA dialect definitions."""

    def test_disassemble_v1_produces_v1_mnemonics(self):
        """Disassembler should produce mnemonics that exist in v1 dialect."""
        asm = Assembler()
        dis = Disassembler()
        v1 = ISADialect.v1()

        bc = asm.assemble("MOVI R0, 42\nIADD R0, R0, R1\nDEC R0\nHALT")
        text = dis.disassemble(bc)

        # Extract mnemonics from disassembly output
        for line in text.strip().split("\n"):
            parts = line.split(": ", 1)
            if len(parts) < 2:
                continue
            instr = parts[1].strip().split()[0]
            if instr.startswith("???"):
                continue
            # Mnemonic should exist in v1 dialect
            self.assertIsNotNone(
                v1.opcode_for(instr),
                f"Disassembler produced unknown mnemonic '{instr}'"
            )

    def test_disassemble_all_v1_opcodes(self):
        """Every v1 opcode should disassemble correctly."""
        dis = Disassembler()
        v1 = ISADialect.v1()

        # Build bytecode for each v1 opcode
        test_cases = {
            "HALT": bytes([0x80]),
            "DEC":  bytes([0x0F, 0x00]),
            "IADD": bytes([0x08, 0x00, 0x01, 0x02]),
            "IMUL": bytes([0x0A, 0x00, 0x01, 0x02]),
            "IDIV": bytes([0x0B, 0x00, 0x01, 0x02]),
            "MOVI": bytes([0x2B, 0x00, 0x01, 0x00]),
            "JNZ":  bytes([0x06, 0x00, 0x01, 0x00]),
        }

        for mn, bc in test_cases.items():
            with self.subTest(mnemonic=mn):
                text = dis.disassemble(bc)
                self.assertIn(mn, text)

    def test_assemble_disassemble_roundtrip(self):
        """Assemble then disassemble should produce readable output."""
        asm = Assembler()
        dis = Disassembler()
        asm_text = "MOVI R0, 42\nMOVI R1, 7\nIADD R0, R0, R1\nHALT"
        bc = asm.assemble(asm_text)
        text = dis.disassemble(bc)
        # Check key instructions are present
        self.assertIn("MOVI R0", text)
        self.assertIn("MOVI R1", text)
        self.assertIn("IADD", text)
        self.assertIn("HALT", text)


# ═════════════════════════════════════════════════════════════════════════════
# 8. Multi-dialect fleet scenarios
# ═════════════════════════════════════════════════════════════════════════════

class TestMultiDialectFleet(unittest.TestCase):
    """Simulate multi-agent fleet scenarios with dialect interoperability."""

    def test_three_dialect_max_subset(self):
        """With 3 dialects at different compatibility levels, find subsets."""
        reg = ISARegistry()
        reg.register(ISADialect.custom("esp32-flux", 1, {
            "HALT": 0x00, "MOVI": 0x30, "ADD": 0x20,
        }))
        reg.register(ISADialect.custom("jetson-flux", 2, {
            "HALT": 0x00, "MOVI": 0x30, "ADD": 0x20,
            "SUB": 0x21, "MUL": 0x22,
        }))

        # At threshold=1.0, each dialect is self-compatible
        subsets = reg.max_compatible_subset(threshold=1.0)
        self.assertTrue(len(subsets) >= 4)  # at least 4 singleton sets

        # At threshold=0.5, should have large sets
        subsets = reg.max_compatible_subset(threshold=0.5)
        largest = max(len(s) for s in subsets)
        self.assertGreaterEqual(largest, 3)

    def test_program_portable_across_subsets(self):
        """A simple program (HALT+MOVI) should be portable across all dialects."""
        reg = ISARegistry()
        reg.register(ISADialect.custom("minimal", 1, {
            "HALT": 0x00, "MOVI": 0x30,
        }))

        v1 = ISADialect.v1()
        t = ISATranslator(v1, reg.get("minimal"))
        bc = make_v1_bytecode(("MOVI", 0, 1), ("HALT",))
        result = t.translate(bc)
        self.assertTrue(result.success)

    def test_fleet_compatibility_degredation(self):
        """Adding more dialects should not break existing compatibility."""
        reg = ISARegistry()
        score_before = reg.compatibility("v1", "v2").score

        reg.register(ISADialect.custom("irrelevant", 99, {"HALT": 0xFE}))
        score_after = reg.compatibility("v1", "v2").score

        self.assertEqual(score_before, score_after)

    def test_conformance_report_includes_all_operations(self):
        """Conformance report should enumerate all canonical operations."""
        v1 = ISADialect.v1()
        cv = ConformanceVector(v1, v1)  # self-conformance
        report = cv.report()
        # v1 covers HALT, DEC, ADD, MUL, DIV, MOVI, JNZ
        self.assertGreaterEqual(report.total_operations, 7)

    def test_build_translator_from_registry_for_all_pairs(self):
        """build_translator should work for all pairs in a populated registry."""
        reg = ISARegistry()
        reg.register(ISADialect.custom("v3", 3, {
            "HALT": 0x00, "ADD": 0x20, "MOVI": 0x30,
        }))
        names = reg.dialect_names
        for src_name in names:
            for tgt_name in names:
                with self.subTest(src=src_name, tgt=tgt_name):
                    t = build_translator(reg, src_name, tgt_name)
                    self.assertIsInstance(t, ISATranslator)


# ═════════════════════════════════════════════════════════════════════════════
# 9. In-place translation ↔ VM execution
# ═════════════════════════════════════════════════════════════════════════════

class TestInPlaceTranslationVM(unittest.TestCase):
    """Verify in-place translation results can still be executed correctly."""

    def test_inplace_translate_then_execute_roundtrip(self):
        """Translate v1→v2→v1 in-place, then execute on VM."""
        v1, v2 = ISADialect.v1(), ISADialect.v2()

        # Build a v1 program: MOVI R0,10; MOVI R1,3; IADD R0,R0,R1; HALT
        bc = bytearray(make_v1_bytecode(
            ("MOVI", 0, 10), ("MOVI", 1, 3), ("IADD", 0, 0, 1), ("HALT",)
        ))

        # Execute original
        vm_before = FluxVM(bytes(bc))
        vm_before.execute()
        r0_before = vm_before.reg(0)

        # Translate v1→v2 in-place
        t_fwd = ISATranslator(v1, v2)
        result_fwd = t_fwd.translate_inplace(bc)
        self.assertTrue(result_fwd.success)

        # Translate v2→v1 in-place (back to v1 opcodes)
        t_back = ISATranslator(v2, v1)
        result_back = t_back.translate_inplace(bc)
        self.assertTrue(result_back.success)

        # Execute after round-trip
        vm_after = FluxVM(bytes(bc))
        vm_after.execute()
        r0_after = vm_after.reg(0)

        self.assertEqual(r0_before, r0_after)
        self.assertEqual(r0_before, 13)

    def test_inplace_preserves_byte_length_for_vm(self):
        """In-place translation must not change bytecode length (VM assumes fixed layout)."""
        v1, v2 = ISADialect.v1(), ISADialect.v2()
        original = make_v1_bytecode(
            ("MOVI", 0, 1), ("IADD", 0, 0, 1), ("DEC", 0), ("HALT",)
        )
        bc = bytearray(original)
        ISATranslator(v1, v2).translate_inplace(bc)
        self.assertEqual(len(bc), len(original))

    def test_nonstrict_inplace_unmapped_preserves_layout(self):
        """Non-strict in-place translation of unmapped opcodes preserves operand layout."""
        v2, v1 = ISADialect.v2(), ISADialect.v1()
        # SUB R0,R1,R2 in v2 → unmapped in v1 → 0xFF + operands preserved
        bc = bytearray([0x21, 0x00, 0x01, 0x02, 0x00])  # SUB + HALT
        t = ISATranslator(v2, v1, strict=False)
        result = t.translate_inplace(bc)
        self.assertEqual(result.unmapped, 1)
        self.assertEqual(bc[0], 0xFF)  # placeholder
        self.assertEqual(bc[1], 0x00)  # R0 preserved
        self.assertEqual(bc[2], 0x01)  # R1 preserved
        self.assertEqual(bc[3], 0x02)  # R2 preserved
        self.assertEqual(bc[4], 0x80)  # HALT translated fine


# ═════════════════════════════════════════════════════════════════════════════
# 10. Op format consistency
# ═════════════════════════════════════════════════════════════════════════════

class TestOpFormatConsistency(unittest.TestCase):
    """Verify that instruction formats match between ISA layer and VM expectations."""

    def test_all_ops_have_format(self):
        """Every canonical Op must have a defined format."""
        for op in Op:
            self.assertIn(op, OP_FORMAT,
                f"Op {op.value} has no defined format in OP_FORMAT")

    def test_format_values_are_sensible(self):
        """Format byte-lengths should be 1, 2, or 4."""
        for fmt in InsnFormat:
            self.assertIn(fmt.value, {1, 2, 4})

    def test_v1_instruction_sizes_match_format_table(self):
        """v1 dialect instruction_size() should match OP_FORMAT."""
        v1 = ISADialect.v1()
        expected = {
            "HALT": 1, "DEC": 2,
            "IADD": 4, "IMUL": 4, "IDIV": 4,
            "MOVI": 4, "JNZ": 4,
        }
        for mn, expected_size in expected.items():
            opcode = v1.opcode_for(mn)
            self.assertEqual(v1.instruction_size(opcode), expected_size,
                f"{mn} size mismatch")

    def test_v2_instruction_sizes_match_format_table(self):
        """v2 dialect instruction_size() should match OP_FORMAT."""
        v2 = ISADialect.v2()
        expected = {
            "ADD": 4, "SUB": 4, "MUL": 4, "DIV": 4,
            "MOVI": 4, "DEC": 2, "JNZ": 4, "HALT": 1,
        }
        for mn, expected_size in expected.items():
            opcode = v2.opcode_for(mn)
            self.assertEqual(v2.instruction_size(opcode), expected_size,
                f"{mn} size mismatch")


# ─── Main ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    unittest.main(verbosity=2)
